### READ ALL MOVIES FROM REPO STUB
GET http://localhost:5000/movies/all
Accept: application/json

### READ BY ID - 1
GET http://localhost:5000/movies/get?id=1
Accept: application/json

### POST NEW MOVIE
POST http://localhost:5000/movies/add
Content-Type: application/json
Accept: */*

{
  "Title": "The Lion King",
  "Rating": "G"
}

